--DailyConfig.luau
return {
	[1] = {
		espresso = 10,
	},
	[2] = {
		espresso = 10,
		milk = 8,
		foam = 5,
	},
	[3] = {
		espresso = 10,
		chocolate = 5,
		teabag = 5,
	},
	[4] = {
		icecream = 10,
		matchapowder = 8,
	},
	[5] = {
		lemon = 5,
		carbonator = 5,
	},
	[6] = {
		cookies = 5,
	},
	[7] = {
		espresso = 10,
		water = 10,
		milk = 10,
		foam = 10,
		ice = 10,
		chocolate = 10,
		teabag = 10,
		icecream = 10,
		matchapowder = 10,
		lemon = 10,
		carbonator = 10,
		cookies = 10,
	},
}
