-- Shared/Configs/IngredientsConfig.luau
return {
	{
		Id = "espresso",
		DisplayName = "Espresso",
		ItemTip = [[A concentrated shot of coffee made by forcing pressurized hot water through finely-ground beans. It has a layer of "crema" (golden-brown foam) on top.]],
		Price = 1,
	},
	{
		Id = "water",
		DisplayName = "Water",
		ItemTip = [[Clean, sterile, and hot drinking water.]],
		Price = 1,
	},
	{
		Id = "milk",
		DisplayName = "Milk",
		ItemTip = [[Freshly milked from local farm cows.]],
		Price = 1,
	},
	{
		Id = "ice",
		DisplayName = "Ice",
		ItemTip = [[Frozen water cubes to chill your beverages.]],
		Price = 2,
	},
	{
		Id = "foam",
		DisplayName = "Foam",
		ItemTip = [[Velvety, aerated milk.]],
		Price = 2,
	},
	{
		Id = "chocolate",
		DisplayName = "Chocolate Powder",
		ItemTip = [[Rich cocoa powder for a sweet, chocolaty kick.]],
		Price = 3,
	},
	{
		Id = "teabag",
		DisplayName = "Tea Bag",
		ItemTip = [[A carefully measured pouch of dried tea leaves.]],
		Price = 3,
	},
	{
		Id = "icecream",
		DisplayName = "Ice Cream",
		ItemTip = [[Sweet, creamy, and frozen vanilla goodness.]],
		Price = 5,
	},
	{
		Id = "matchapowder",
		DisplayName = "Matcha Powder",
		ItemTip = [[Finely ground powder of specially grown green tea leaves.]],
		Price = 9,
	},
	{
		Id = "lemon",
		DisplayName = "Lemon Slice",
		ItemTip = [[A freshly cut slice of zesty citrus.]],
		Price = 15,
	},
	{
		Id = "boba",
		DisplayName = "Boba Pearls",
		ItemTip = [[Chewy tapioca pearls sweetened with brown sugar.]],
		Price = 15,
	},
	{
		Id = "carbonator",
		DisplayName = "Carbonator",
		ItemTip = [[Adds bubbly carbonation to any liquid.]],
		Price = 20,
	},
}
